[package]
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>", "Teigan Rosen"]
edition = "2018"
name = "warmer-pale-fire"
version = "0.2.0"

[dependencies]
anyhow = "1.0"
mottle = "0.5.0"
tincture = "1.0"
